@startuml

!includeurl https://raw.githubusercontent.com/k-vaughn/its-reference-model/master/intersectionleg.puml

class IntersectionGeometry {
	- regionIdentifier
	- identifier
	+ descriptiveName
}

IntersectionGeometry *--> "2..* legs" IntersectionLeg
IntersectionGeometry --> "1 refPoint" GeoPosition

@enduml
