@startuml

class LaneIntersectionConnection {
	sourceRegion
	sourceIntersection
	sourceLane
	destRegion
	destIntersection
	destLane
	signalGroup [0..1]
	userClass [0..1]
	connectionID [0..1]
}

@enduml
