@startuml

!includeurl https://raw.githubusercontent.com/k-vaughn/its-reference-model/master/lanenode.puml
!includeurl https://raw.githubusercontent.com/k-vaughn/its-reference-model/master/regulatoryspeed.puml

class LaneSegment {
	identifier
	attributes[0..8]
	endPointAngle [0..1]
	crownPointCentre [0..1]
	crownPointLeft [0..1]
	crownPointRight [0..1]
	laneAngle [0..1]
	width [0..1]
	elevation [0..1]
}

LaneSegment *--> "2 nodes" LaneNode
LaneSegment --> "1..9 speedLimits" RegulatorySpeedLimit

@enduml
