@startuml
!includeurl https://raw.githubusercontent.com/k-vaughn/its-reference-model/master/geoposition.puml

class LaneNode {
	- identifier
	+ attributes[]
}

note bottom: a node can be designated\nas a stop line using attributes

LaneNode --> "1 location" GeoPosition

@enduml
